import csv
with open('23.csv','a+',newline='',encoding='utf8') as f:
    m=csv.writer(f)
    m.writerow(['Taotys pizza',299])
    m.writerow(['Taotys shabu',399])
    m.writerow(['Taotys grill',499])
    m.writerow(['Taotys boba',99])
    m.writerow(['Taotys burger',199])
    m.writerow(['Taotys smoothie',99])
    m.writerow(['Taotys brownie',99])
    m.writerow(['Taotys ice-cream',89])
    m.writerow(['Taotys coffee',69])
    m.writerow(['Taotys Durianmontong',1299])
    m.writerow(['Taotys mala',299])
    m.writerow(['Taotys toasty',299])
    m.writerow(['Taotys bingsu',399])
    m.writerow(['Taotys Convinient store',499])
    m.writerow(['Taotys water',99])
    m.writerow(['Taotys bar&restaurant',199])
    m.writerow(['Taotys sushi',99])
    m.writerow(['Taotys bakery',99])
    m.writerow(['Taotys gelato',89])
    m.writerow(['Taotys fried chicken',69])
    m.writerow(['Taotys salmon hub',1299])
    m.writerow(['Taotys pasta',299])
