import tkinter as tk 
root= tk.Tk()
root.config(bg='lightgrey')
root.title('HOMEWORK GUI')
#root.geometry('600x400+100+100')
label1 =tk.Label(text='Name : Leelings Atitanan',fg='black',font=50,bg='yellow')
label1.grid(row=0,column=0,sticky='we',ipady=25,columnspan=4,pady=2)
label2 =tk.Label(text='Major : E-AI Artificial intelligent',fg='black',font=50,bg='limegreen')
label2.grid(row=1,column=0,sticky='we',ipady=25,columnspan=4,pady=2)
label3 =tk.Label(bg='violetred1')
label3.grid(row=3,column=0,ipadx=50,ipady=50,padx=2)
label4 =tk.Label(bg='maroon1')
label4.grid(row=3,column=1,ipadx=50,ipady=50,padx=2)
label5 =tk.Label(bg='DeepPink1')
label5.grid(row=3,column=2,ipadx=50,ipady=50,padx=2)
label6 =tk.Label(bg='DeepPink2')
label6.grid(row=3,column=3,ipadx=50,ipady=50,padx=2)
label7 =tk.Label(text='SPSM',fg='black',bg='white')
label7.grid(row=4,column=0,sticky='we',ipady=25,columnspan=4,pady=2)
label8 =tk.Label(text='OK',fg='white',bg='black')
label8.grid(row=5,column=0,ipadx=40,ipady=15,columnspan=4,pady=5)
root.mainloop()